# Generated by Django 2.2.2 on 2019-06-11 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_settlement', models.CharField(max_length=100, verbose_name='Пункт відправлення')),
                ('arrive_settlement', models.CharField(max_length=100, verbose_name='Пункт прибуття')),
                ('depart_time', models.DateTimeField(verbose_name='Час відправлення')),
                ('arrive_time', models.DateTimeField(verbose_name='Час прибуття')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('count_of_seats', models.SmallIntegerField(verbose_name='Кільсть сидінь')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.SmallIntegerField(verbose_name='Номер сидіння')),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BusLine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
