# Generated by Django 2.2.2 on 2019-06-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busline',
            options={'verbose_name': 'рейс', 'verbose_name_plural': 'рейси'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'квиток', 'verbose_name_plural': 'квитки'},
        ),
    ]
